export const todoTemp = [
    {   
        id: 1,
        topic: 'Pelatihan Microsoft Office Excel', 
        status: 'Online', 
        classCode: 'LB-02', 
        zoomLink: 'https://binus.zoom.us/j/97970210339?pwd=NU04NWMxcDBta200TTBEODBp...', 
        date: '28 January 2024',
        time: '10:00-11:30',
        material: 'https://scholar.google.com/',
        video1: 'https://www.youtube.com/watch?v=4NIDgp9ekVk',
        video2: 'https://www.youtube.com/watch?v=WKjdTLwJ6TY',
    }, 
    {   
        id: 2,
        topic: 'Pelatihan Microsoft Office Excel', 
        status: 'Online', 
        classCode: 'LC-02', 
        zoomLink: 'https://binus.zoom.us/j/97970210339?pwd=NU04NWMxcDBta200TTBEODBp...', 
        date: '20 March 2024',
        time: '10:00-11:30',
        material: 'https://scholar.google.com/',
        video1: 'https://www.youtube.com/watch?v=jfKfPfyJRdk',
        video2: 'https://www.youtube.com/watch?v=IJT51et7owQ',
    },  
    {   
        id: 3,
        topic: 'Internet untuk Bisnis', 
        status: 'Online', 
        classCode: 'LD-02', 
        zoomLink: 'https://binus.zoom.us/j/97970210339?pwd=NU04NWMxcDBta200TTBEODBp...', 
        date: '4 February 2024',
        time: '10:00-11:30',
        material: 'https://scholar.google.com/',
        video1: 'https://www.youtube.com/watch?v=12b033YER-8&t=124s',
        video2: 'https://www.youtube.com/watch?v=WKjdTLwJ6TY',
    },
]


export const doneTemp = [
    {   
        id: 1,
        topic: 'Internet untuk Bisnis', 
        status: 'Offline', 
        classCode: 'LB-02', 
        place: 'Menara Tower', 
        date: '22 October 2023',
        time: '10:00-11:30',
        material: 'https://scholar.google.com/',
        video1: 'https://www.youtube.com/watch?v=IJT51et7owQ',
        video2: 'https://www.youtube.com/watch?v=WKjdTLwJ6TY', 
    },
    {   
        id: 2,
        topic: 'Pelatihan Microsoft Office Excel', 
        status: 'Online', 
        classCode: 'LC-02', 
        zoomLink: 'https://binus.zoom.us/j/97970210339?pwd=NU04NWMxcDBta200TTBEODBp...', 
        date: '22 November 2023',
        time: '10:00-11:30',
        material: 'https://scholar.google.com/',
        video1: 'https://www.youtube.com/watch?v=jfKfPfyJRdk',
        video2: 'https://www.youtube.com/watch?v=IJT51et7owQ',
    }, 
    {   
        id: 3,
        topic: 'Internet untuk Bisnis', 
        status: 'Offline', 
        classCode: 'LD-02', 
        place: 'Auditorium', 
        date: '4 December 2023',
        time: '10:00-11:30',
        material: 'https://scholar.google.com/',
        video1: 'https://www.youtube.com/watch?v=12b033YER-8&t=124s',
        video2: 'https://www.youtube.com/watch?v=WKjdTLwJ6TY',
    },
]

